Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "app" do |app|
    app.vm.hostname = "app-vm"
    app.vm.network "private_network", ip: "192.168.56.10"
    app.vm.network "forwarded_port", guest: 8080, host: 8080

    app.vm.provider "virtualbox" do |vb|
      vb.name = "app-vm"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db-vm"
    db.vm.network "private_network", ip: "192.168.56.11"

    db.vm.provider "virtualbox" do |vb|
      vb.name = "db-vm"
      vb.memory = 1024
      vb.cpus = 1
    end
  end
end

